spring:
  datasource:
    username: postgres
    password: 12345678
    url: jdbc:postgresql://localhost:5432/customer_info

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
      ddl-auto: none


  flyway:
    schemas: customer_info
    baseline-on-migrate: true
    enabled: true