create table RESTAURANTS
(
    ID              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RESTAURANT_NAME VARCHAR(255) NOT NULL,
    CATEGORY        VARCHAR(13)  NOT NULL,
    CITY            VARCHAR(255)
);

CREATE TABLE REVIEWS
(
    ID      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CONTENT VARCHAR(255) NOT NULL,
    RATING  INTEGER      NOT NULL,
    RESTAURANT_ID BIGINT REFERENCES RESTAURANTS
);

-- Restaurants

INSERT INTO public.restaurants(
	id, restaurant_name, category, city)
	VALUES (1, 'Hungry Heaven', 'Japanese', 'Lisbon');

INSERT INTO public.restaurants(
	id, restaurant_name, category, city)
	VALUES (2, 'All You Can Eat', 'Brazilian', 'Porto');

INSERT INTO public.restaurants(
	id, restaurant_name, category, city)
	VALUES (3, 'Hungry Heaven', 'Japanese', 'Paris');

INSERT INTO public.restaurants(
	id, restaurant_name, category, city)
	VALUES (4, 'Tropicana', 'Portuguese', 'Lisbon');

INSERT INTO public.restaurants(
	id, restaurant_name, category, city)
	VALUES (5, 'Subway', 'FastFood', 'Lisbon');

-- Reviews

INSERT INTO public.reviews(
	id, content, rating, restaurant_id)
	VALUES (1, 'Awesome food!', 5, 1);

INSERT INTO public.reviews(
	id, content, rating, restaurant_id)
	VALUES (2, 'Good food!', 4, 1);

INSERT INTO public.reviews(
	id, content, rating, restaurant_id)
	VALUES (3, 'Ok food!', 5, 1);

INSERT INTO public.reviews(
	id, content, rating, restaurant_id)
	VALUES (4, '"Taste food!"', 3, 1);

INSERT INTO public.reviews(
	id, content, rating, restaurant_id)
	VALUES (5, '"Nice food!"', 3, 1);

INSERT INTO public.reviews(
	id, content, rating, restaurant_id)
	VALUES (6, '"Awesome food!"', 5, 2);

INSERT INTO public.reviews(
	id, content, rating, restaurant_id)
	VALUES (7, '"Good food!"', 4, 2);

INSERT INTO public.reviews(
	id, content, rating, restaurant_id)
	VALUES (8, '"Ok food!"', 5, 2);

INSERT INTO public.reviews(
	id, content, rating, restaurant_id)
	VALUES (9, '"Taste food!"', 3, 3);

INSERT INTO public.reviews(
	id, content, rating, restaurant_id)
	VALUES (10, '"Nice food!"', 3, 3);


